# Generated by Django 5.2.1 on 2025-05-21 11:36

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.IntegerField(max_length=10, verbose_name='کد ملی')),
                ('phone_number', models.IntegerField(max_length=11, verbose_name='شماره تماس')),
                ('age', models.IntegerField(max_length=3, verbose_name='سن')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='گروه خونی')),
                ('kdpi', models.FloatField(help_text='عددی بین 0 تا 100', verbose_name='KDPI')),
                ('recipient_blood_group', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=2, verbose_name='گروه خونی مناسب برای گیرنده')),
                ('min_recipient_age', models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', max_length=3, verbose_name='حداقل سن مناسب برای گیرنده')),
                ('max_recipient_age', models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', max_length=3, verbose_name='حداکثر سن مناسب برای گیرنده')),
            ],
            options={
                'verbose_name': 'اهدا کننده',
                'verbose_name_plural': 'اهدا کنندگان',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.IntegerField(max_length=10, verbose_name='کد ملی')),
                ('phone_number', models.IntegerField(max_length=11, verbose_name='شماره تماس')),
                ('age', models.IntegerField(max_length=3, verbose_name='سن')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='گروه خونی')),
                ('waiting_list', models.IntegerField(max_length=3)),
                ('dialysis_duration', models.IntegerField(max_length=3)),
                ('previous_donation', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('medical_urgency', models.CharField(choices=[('1', 'no access'), ('2', 'cardiomyopathy')], max_length=1)),
                ('candidate_for_2_kidney_TX', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('candidate_for_kidney_after_other_organ_TX', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('cpra', models.CharField(choices=[('1', '≥ 98%'), ('2', '95-97%'), ('3', 'desensitized')], max_length=1)),
                ('point', models.FloatField(verbose_name='امتیاز')),
            ],
            options={
                'verbose_name': 'گیرنده',
                'verbose_name_plural': 'گیرندگان',
            },
        ),
    ]
