# Generated by Django 5.2.1 on 2025-07-01 14:52

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HlaA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3, verbose_name='HLA A')),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HlaB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3, verbose_name='HLA B')),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HlaDQB1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3, verbose_name='HLA DQB1')),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HlaDRB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3, verbose_name='HLA DRB')),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HlaDRB1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3, verbose_name='HLA DRB1')),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.IntegerField(verbose_name='کد ملی')),
                ('phone_number', models.IntegerField(verbose_name='شماره تماس')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='گروه خونی')),
                ('kdpi', models.FloatField(help_text='عددی بین 0 تا 100', verbose_name='KDPI')),
                ('recipient_blood_group', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=2, verbose_name='گروه خونی مناسب برای گیرنده')),
                ('min_recipient_age', models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداقل سن مناسب برای گیرنده')),
                ('max_recipient_age', models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداکثر سن مناسب برای گیرنده')),
                ('hla_a_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_1_donor', to='referees.hlaa', verbose_name='HLA A (allele 1)')),
                ('hla_a_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_2_donor', to='referees.hlaa', verbose_name='HLA A (allele 2)')),
                ('hla_b_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_1_donor', to='referees.hlaa', verbose_name='HLA B (allele 1)')),
                ('hla_b_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_2_donor', to='referees.hlaa', verbose_name='HLA B (allele 2)')),
                ('hla_dqb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_1_donor', to='referees.hlaa', verbose_name='HLA DQB1 (allele 1)')),
                ('hla_dqb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_2_donor', to='referees.hlaa', verbose_name='HLA DQB1 (allele 2)')),
                ('hla_drb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_1_donor', to='referees.hlaa', verbose_name='HLA DRB1 (allele 1)')),
                ('hla_drb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_2_donor', to='referees.hlaa', verbose_name='HLA DRB1 (allele 2)')),
                ('hla_drb_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_donor', to='referees.hlaa', verbose_name='HLA DRB (allele 1)')),
                ('hla_drb_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_donor', to='referees.hlaa', verbose_name='HLA DRB (allele 2)')),
            ],
            options={
                'verbose_name': 'اهدا کننده',
                'verbose_name_plural': 'اهدا کنندگان',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.IntegerField(verbose_name='کد ملی')),
                ('phone_number', models.IntegerField(verbose_name='شماره تماس')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='گروه خونی')),
                ('waiting_list', models.CharField(max_length=10)),
                ('dialysis_duration', models.CharField(max_length=10)),
                ('previous_donation', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('medical_urgency', models.CharField(choices=[('1', 'no access'), ('2', 'cardiomyopathy'), ('3', 'none')], max_length=1)),
                ('candidate_for_2_kidney_TX', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('candidate_for_kidney_after_other_organ_TX', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('cpra', models.CharField(choices=[('1', '≥ 98%'), ('2', '95-97%'), ('3', 'none')], max_length=1)),
                ('desensitized', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3)),
                ('point', models.FloatField(verbose_name='امتیاز')),
                ('hla_a_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_1_recipient', to='referees.hlaa', verbose_name='HLA A (allele 1)')),
                ('hla_a_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_2_recipient', to='referees.hlaa', verbose_name='HLA A (allele 2)')),
                ('hla_b_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_1_recipient', to='referees.hlaa', verbose_name='HLA B (allele 1)')),
                ('hla_b_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_2_recipient', to='referees.hlaa', verbose_name='HLA B (allele 2)')),
                ('hla_dqb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_1_recipient', to='referees.hlaa', verbose_name='HLA DQB1 (allele 1)')),
                ('hla_dqb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_2_recipient', to='referees.hlaa', verbose_name='HLA DQB1 (allele 2)')),
                ('hla_drb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_1_recipient', to='referees.hlaa', verbose_name='HLA DRB1 (allele 1)')),
                ('hla_drb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_2_recipient', to='referees.hlaa', verbose_name='HLA DRB1 (allele 2)')),
                ('hla_drb_1', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_recipient', to='referees.hlaa', verbose_name='HLA DRB (allele 1)')),
                ('hla_drb_2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_recipient', to='referees.hlaa', verbose_name='HLA DRB (allele 2)')),
            ],
            options={
                'verbose_name': 'گیرنده',
                'verbose_name_plural': 'گیرندگان',
            },
        ),
    ]
