# Generated by Django 5.2.1 on 2025-07-01 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='hla_b_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_1_donor', to='referees.hlab', verbose_name='HLA B (allele 1)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hla_b_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_2_donor', to='referees.hlab', verbose_name='HLA B (allele 2)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hla_dqb1_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_1_donor', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 1)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hla_dqb1_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_2_donor', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 2)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hla_drb1_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_1_donor', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 1)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hla_drb1_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_2_donor', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 2)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hla_drb_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_donor', to='referees.hladrb', verbose_name='HLA DRB (allele 1)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hla_drb_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_donor', to='referees.hladrb', verbose_name='HLA DRB (allele 2)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_b_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_1_recipient', to='referees.hlab', verbose_name='HLA B (allele 1)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_b_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_2_recipient', to='referees.hlab', verbose_name='HLA B (allele 2)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_dqb1_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_1_recipient', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 1)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_dqb1_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_2_recipient', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 2)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_drb1_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_1_recipient', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 1)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_drb1_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_2_recipient', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 2)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_drb_1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_recipient', to='referees.hladrb', verbose_name='HLA DRB (allele 1)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_drb_2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_recipient', to='referees.hladrb', verbose_name='HLA DRB (allele 2)'),
        ),
    ]
