# Generated by Django 5.2.1 on 2025-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='age',
            field=models.IntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='max_recipient_age',
            field=models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداکثر سن مناسب برای گیرنده'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='min_recipient_age',
            field=models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداقل سن مناسب برای گیرنده'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='national_code',
            field=models.IntegerField(verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='phone_number',
            field=models.IntegerField(verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='age',
            field=models.IntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='dialysis_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='national_code',
            field=models.IntegerField(verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone_number',
            field=models.IntegerField(verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='waiting_list',
            field=models.IntegerField(),
        ),
    ]
