# Generated by Django 5.2.1 on 2026-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='read_uam_from',
            field=models.CharField(choices=[('1', 'ارسال دستی'), ('2', 'از فایل های ارسالی')], default='1', max_length=1, verbose_name='تحلیل UAM از؟'),
        ),
    ]
