# Generated by Django 5.2.1 on 2025-07-01 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0002_alter_donor_hla_b_1_alter_donor_hla_b_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='hla_drb_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_donor', to='referees.hladrb', verbose_name='HLA DRB (allele 1)'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='hla_drb_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_donor', to='referees.hladrb', verbose_name='HLA DRB (allele 2)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_drb_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_recipient', to='referees.hladrb', verbose_name='HLA DRB (allele 1)'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_drb_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_recipient', to='referees.hladrb', verbose_name='HLA DRB (allele 2)'),
        ),
    ]
