# Generated by Django 5.2.1 on 2026-05-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0002_alter_recipient_read_uam_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='search_donor',
            field=models.CharField(choices=[('1', 'Both Types Of Donors'), ('2', 'Cadaver Donors'), ('3', 'Living Donors')], default='1', max_length=1, verbose_name='جستجو از اهداکنندگان'),
        ),
    ]
