# Generated by Django 5.2.1 on 2025-06-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0002_recipient_hla_matching_and_mismatch_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='desensitized',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='cpra',
            field=models.CharField(choices=[('1', '≥ 98%'), ('2', '95-97%'), ('3', 'none')], max_length=1),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='medical_urgency',
            field=models.CharField(choices=[('1', 'no access'), ('2', 'cardiomyopathy'), ('3', 'none')], max_length=1),
        ),
    ]
