# Generated by Django 5.2.1 on 2025-06-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0003_recipient_desensitized_alter_recipient_cpra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='desensitized',
            field=models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='hla_matching_and_mismatch_score',
            field=models.IntegerField(verbose_name='HLA matching and mismatch score'),
        ),
    ]
