# Generated by Django 5.2.1 on 2025-07-01 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0003_alter_donor_hla_drb_1_alter_donor_hla_drb_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hladrb',
            name='type',
        ),
    ]
