# Generated by Django 5.2.1 on 2026-05-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0003_recipient_search_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='cpra',
            field=models.CharField(blank=True, choices=[('1', '≥ 98%'), ('2', '95-97%'), ('3', '80-94%'), ('4', '21-79%'), ('5', '1-20%'), ('6', '0%')], max_length=1, null=True),
        ),
    ]
