# Generated by Django 5.2.1 on 2025-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0004_remove_hladrb_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlaa',
            name='value',
            field=models.CharField(max_length=3, unique=True, verbose_name='HLA A'),
        ),
        migrations.AlterField(
            model_name='hlab',
            name='value',
            field=models.CharField(max_length=3, unique=True, verbose_name='HLA B'),
        ),
        migrations.AlterField(
            model_name='hladqb1',
            name='value',
            field=models.CharField(max_length=3, unique=True, verbose_name='HLA DQB1'),
        ),
        migrations.AlterField(
            model_name='hladrb',
            name='value',
            field=models.CharField(max_length=3, unique=True, verbose_name='HLA DRB'),
        ),
        migrations.AlterField(
            model_name='hladrb1',
            name='value',
            field=models.CharField(max_length=3, unique=True, verbose_name='HLA DRB1'),
        ),
    ]
