# Generated by Django 5.2.1 on 2026-05-14 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0004_alter_recipient_cpra'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_i_pdf', models.FileField(blank=True, null=True, upload_to='recipient_pdf/', verbose_name='Class I PDF')),
                ('class_ii_pdf', models.FileField(blank=True, null=True, upload_to='recipient_pdf/', verbose_name='Class II PDF')),
                ('hla_a_uam_history', models.ManyToManyField(blank=True, related_name='hla_a_1_uam_history', to='referees.hlaa', verbose_name='HLA A (UAM)')),
                ('hla_b_uam_history', models.ManyToManyField(blank=True, related_name='hla_b_1_uam_history', to='referees.hlab', verbose_name='HLA B (UAM)')),
                ('hla_dqb1_uam_history', models.ManyToManyField(blank=True, related_name='hla_dqb1_1_uam_history', to='referees.hladqb1', verbose_name='HLA DQB1 (UAM)')),
                ('hla_drb1_uam_history', models.ManyToManyField(blank=True, related_name='hla_drb1_1_uam_history', to='referees.hladrb1', verbose_name='HLA DRB1 (UAM)')),
                ('hla_drb_uam_history', models.ManyToManyField(blank=True, related_name='hla_drb_1_uam_history', to='referees.hladrb', verbose_name='HLA DRB (UAM)')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_history_call', to='referees.recipient', verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'history call',
                'verbose_name_plural': 'history calls',
            },
        ),
    ]
