# Generated by Django 5.2.1 on 2025-07-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0005_alter_hlaa_value_alter_hlab_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlaa',
            name='type',
            field=models.CharField(choices=[('1', 'COMMON'), ('2', 'INTERMEDIATE'), ('3', 'UNCOMMON')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hlab',
            name='type',
            field=models.CharField(choices=[('1', 'COMMON'), ('2', 'INTERMEDIATE'), ('3', 'UNCOMMON')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hladqb1',
            name='type',
            field=models.CharField(choices=[('1', 'COMMON'), ('2', 'INTERMEDIATE'), ('3', 'UNCOMMON')], max_length=1),
        ),
        migrations.AlterField(
            model_name='hladrb1',
            name='type',
            field=models.CharField(choices=[('1', 'COMMON'), ('2', 'INTERMEDIATE'), ('3', 'UNCOMMON')], max_length=1),
        ),
    ]
