# Generated by Django 5.2.1 on 2026-05-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0005_historycall'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadaverdonor',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='دیتای تستی'),
        ),
        migrations.AddField(
            model_name='donortest',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='دیتای تستی'),
        ),
        migrations.AddField(
            model_name='livingdonor',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='دیتای تستی'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='دیتای تستی'),
        ),
        migrations.AddField(
            model_name='recipienttest',
            name='is_test',
            field=models.BooleanField(default=False, verbose_name='دیتای تستی'),
        ),
    ]
