# Generated by Django 5.2.1 on 2026-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0006_cadaverdonor_is_test_donortest_is_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadaverdonor',
            name='deactivate',
            field=models.BooleanField(default=False, verbose_name='غیرفعال سازی'),
        ),
        migrations.AddField(
            model_name='livingdonor',
            name='deactivate',
            field=models.BooleanField(default=False, verbose_name='غیرفعال سازی'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='deactivate',
            field=models.BooleanField(default=False, verbose_name='غیرفعال سازی'),
        ),
    ]
