# Generated by Django 5.2.1 on 2025-07-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0006_alter_hlaa_type_alter_hlab_type_alter_hladqb1_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hlaa',
            name='value',
            field=models.CharField(max_length=20, unique=True, verbose_name='HLA A'),
        ),
        migrations.AlterField(
            model_name='hlab',
            name='value',
            field=models.CharField(max_length=20, unique=True, verbose_name='HLA B'),
        ),
        migrations.AlterField(
            model_name='hladqb1',
            name='value',
            field=models.CharField(max_length=20, unique=True, verbose_name='HLA DQB1'),
        ),
        migrations.AlterField(
            model_name='hladrb',
            name='value',
            field=models.CharField(max_length=20, unique=True, verbose_name='HLA DRB'),
        ),
        migrations.AlterField(
            model_name='hladrb1',
            name='value',
            field=models.CharField(max_length=20, unique=True, verbose_name='HLA DRB1'),
        ),
    ]
