# Generated by Django 5.2.1 on 2025-07-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0007_alter_hlaa_value_alter_hlab_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hla_a_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_1_donor_test', to='referees.hlaa', verbose_name='HLA A (allele 1)')),
                ('hla_a_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_2_donor_test', to='referees.hlaa', verbose_name='HLA A (allele 2)')),
                ('hla_b_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_1_donor_test', to='referees.hlab', verbose_name='HLA B (allele 1)')),
                ('hla_b_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_2_donor_test', to='referees.hlab', verbose_name='HLA B (allele 2)')),
                ('hla_dqb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_1_donor_test', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 1)')),
                ('hla_dqb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_2_donor_test', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 2)')),
                ('hla_drb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_1_donor_test', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 1)')),
                ('hla_drb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_2_donor_test', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 2)')),
                ('hla_drb_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_donor_test', to='referees.hladrb', verbose_name='HLA DRB (allele 1)')),
                ('hla_drb_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_donor_test', to='referees.hladrb', verbose_name='HLA DRB (allele 2)')),
            ],
            options={
                'verbose_name': 'اهدا کننده تستی',
                'verbose_name_plural': 'اهدا کنندگان تستی',
            },
        ),
        migrations.CreateModel(
            name='RecipientTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hla_a_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_1_recipient_test', to='referees.hlaa', verbose_name='HLA A (allele 1)')),
                ('hla_a_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_2_recipient_test', to='referees.hlaa', verbose_name='HLA A (allele 2)')),
                ('hla_b_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_1_recipient_test', to='referees.hlab', verbose_name='HLA B (allele 1)')),
                ('hla_b_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_2_recipient_test', to='referees.hlab', verbose_name='HLA B (allele 2)')),
                ('hla_dqb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_1_recipient_test', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 1)')),
                ('hla_dqb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_2_recipient_test', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 2)')),
                ('hla_drb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_1_recipient_test', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 1)')),
                ('hla_drb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_2_recipient_test', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 2)')),
                ('hla_drb_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_recipient_test', to='referees.hladrb', verbose_name='HLA DRB (allele 1)')),
                ('hla_drb_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_recipient_test', to='referees.hladrb', verbose_name='HLA DRB (allele 2)')),
            ],
            options={
                'verbose_name': 'گیرنده تستی',
                'verbose_name_plural': 'گیرندگان تستی',
            },
        ),
    ]
