# Generated by Django 5.2.1 on 2025-07-29 07:20

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0008_donortest_recipienttest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadaverDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.IntegerField(verbose_name='کد ملی')),
                ('phone_number', models.IntegerField(verbose_name='شماره تماس')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='گروه خونی')),
                ('recipient_blood_group', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=2, verbose_name='گروه خونی مناسب برای گیرنده')),
                ('min_recipient_age', models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداقل سن مناسب برای گیرنده')),
                ('max_recipient_age', models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداکثر سن مناسب برای گیرنده')),
                ('kdpi', models.FloatField(help_text='عددی بین 0 تا 100', verbose_name='KDPI')),
                ('hla_a_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_1_%(class)s', to='referees.hlaa', verbose_name='HLA A (allele 1)')),
                ('hla_a_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_2_%(class)s', to='referees.hlaa', verbose_name='HLA A (allele 2)')),
                ('hla_b_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_1_%(class)s', to='referees.hlab', verbose_name='HLA B (allele 1)')),
                ('hla_b_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_2_%(class)s', to='referees.hlab', verbose_name='HLA B (allele 2)')),
                ('hla_dqb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_1_%(class)s', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 1)')),
                ('hla_dqb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_2_%(class)s', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 2)')),
                ('hla_drb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_1_%(class)s', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 1)')),
                ('hla_drb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_2_%(class)s', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 2)')),
                ('hla_drb_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_%(class)s', to='referees.hladrb', verbose_name='HLA DRB (allele 1)')),
                ('hla_drb_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_%(class)s', to='referees.hladrb', verbose_name='HLA DRB (allele 2)')),
            ],
            options={
                'verbose_name': 'اهدا کننده مرگ مغزی',
                'verbose_name_plural': 'اهدا کنندگان مرگ مغزی',
            },
        ),
        migrations.CreateModel(
            name='LivingDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.IntegerField(verbose_name='کد ملی')),
                ('phone_number', models.IntegerField(verbose_name='شماره تماس')),
                ('age', models.IntegerField(verbose_name='سن')),
                ('blood_group', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2, verbose_name='گروه خونی')),
                ('recipient_blood_group', multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=2, verbose_name='گروه خونی مناسب برای گیرنده')),
                ('min_recipient_age', models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداقل سن مناسب برای گیرنده')),
                ('max_recipient_age', models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداکثر سن مناسب برای گیرنده')),
                ('hla_a_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_1_%(class)s', to='referees.hlaa', verbose_name='HLA A (allele 1)')),
                ('hla_a_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_2_%(class)s', to='referees.hlaa', verbose_name='HLA A (allele 2)')),
                ('hla_b_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_1_%(class)s', to='referees.hlab', verbose_name='HLA B (allele 1)')),
                ('hla_b_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_2_%(class)s', to='referees.hlab', verbose_name='HLA B (allele 2)')),
                ('hla_dqb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_1_%(class)s', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 1)')),
                ('hla_dqb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_2_%(class)s', to='referees.hladqb1', verbose_name='HLA DQB1 (allele 2)')),
                ('hla_drb1_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_1_%(class)s', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 1)')),
                ('hla_drb1_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_2_%(class)s', to='referees.hladrb1', verbose_name='HLA DRB1 (allele 2)')),
                ('hla_drb_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_%(class)s', to='referees.hladrb', verbose_name='HLA DRB (allele 1)')),
                ('hla_drb_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_2_%(class)s', to='referees.hladrb', verbose_name='HLA DRB (allele 2)')),
            ],
            options={
                'verbose_name': 'اهدا کننده زنده',
                'verbose_name_plural': 'اهدا کنندگان زنده',
            },
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
