# Generated by Django 5.2.1 on 2026-09-02 17:17

import referees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0009_donortest_creator_groups_donortest_creator_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadaverdonor',
            name='pcr_based_pdf',
            field=models.FileField(blank=True, null=True, upload_to=referees.models.upload_donor_pdf_path, verbose_name='PCR Based PDF'),
        ),
        migrations.AlterField(
            model_name='historycall',
            name='class_i_pdf',
            field=models.FileField(blank=True, null=True, upload_to=referees.models.upload_recipient_pdf_path, verbose_name='Class I PDF'),
        ),
        migrations.AlterField(
            model_name='historycall',
            name='class_ii_pdf',
            field=models.FileField(blank=True, null=True, upload_to=referees.models.upload_recipient_pdf_path, verbose_name='Class II PDF'),
        ),
        migrations.AlterField(
            model_name='livingdonor',
            name='pcr_based_pdf',
            field=models.FileField(blank=True, null=True, upload_to=referees.models.upload_donor_pdf_path, verbose_name='PCR Based PDF'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='class_i_pdf',
            field=models.FileField(blank=True, null=True, upload_to=referees.models.upload_recipient_pdf_path, verbose_name='Class I PDF'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='class_ii_pdf',
            field=models.FileField(blank=True, null=True, upload_to=referees.models.upload_recipient_pdf_path, verbose_name='Class II PDF'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='pcr_based_pdf',
            field=models.FileField(blank=True, null=True, upload_to=referees.models.upload_recipient_pdf_path, verbose_name='PCR Based PDF'),
        ),
    ]
