# Generated by Django 5.2.1 on 2025-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0009_cadaverdonor_livingdonor_delete_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadaverdonor',
            name='status',
            field=models.CharField(choices=[('1', 'Cadaver Donor'), ('2', 'Living Donor')], default='1', help_text='این مقدار توسط سیستیم تعین می گردد', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='livingdonor',
            name='status',
            field=models.CharField(choices=[('1', 'Cadaver Donor'), ('2', 'Living Donor')], default='1', help_text='این مقدار توسط سیستیم تعین می گردد', max_length=1, verbose_name='وضعیت'),
        ),
    ]
