# Generated by Django 5.2.1 on 2025-07-31 05:24

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0010_cadaverdonor_status_livingdonor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donortest',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='donortest',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='donor_blood_group',
            field=multiselectfield.db.fields.MultiSelectField(default=['A', 'AB'], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=200, verbose_name='گروه خونی مناسب برای دهنده'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='max_donor_age',
            field=models.IntegerField(default=0, help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداکثر سن مناسب برای دهنده'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='min_donor_age',
            field=models.IntegerField(default=0, help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداقل سن مناسب برای دهنده'),
        ),
        migrations.AddField(
            model_name='recipienttest',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام'),
        ),
        migrations.AddField(
            model_name='recipienttest',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='cadaverdonor',
            name='recipient_blood_group',
            field=multiselectfield.db.fields.MultiSelectField(help_text='این مقدار توسط سیستیم تعین می گردد', max_length=200, verbose_name='گروه خونی مناسب برای گیرنده'),
        ),
        migrations.AlterField(
            model_name='livingdonor',
            name='recipient_blood_group',
            field=multiselectfield.db.fields.MultiSelectField(help_text='این مقدار توسط سیستیم تعین می گردد', max_length=200, verbose_name='گروه خونی مناسب برای گیرنده'),
        ),
    ]
