# Generated by Django 5.2.1 on 2026-09-28 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0010_alter_cadaverdonor_pcr_based_pdf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientUAMMFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfi', models.PositiveIntegerField(help_text='بیشترین MFI بین allele های این HLA', verbose_name='MFI')),
                ('hla_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uam_mfi_values', to='referees.hlaa')),
                ('hla_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uam_mfi_values', to='referees.hlab')),
                ('hla_dqb1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uam_mfi_values', to='referees.hladqb1')),
                ('hla_drb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uam_mfi_values', to='referees.hladrb')),
                ('hla_drb1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uam_mfi_values', to='referees.hladrb1')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uam_mfi_values', to='referees.recipient', verbose_name='گیرنده')),
            ],
            options={
                'verbose_name': 'تیتر MFI برای HLA UAM',
                'verbose_name_plural': 'تیترهای MFI برای HLA UAM',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('hla_a__isnull', False), ('hla_b__isnull', True), ('hla_dqb1__isnull', True), ('hla_drb1__isnull', True), ('hla_drb__isnull', True)), models.Q(('hla_a__isnull', True), ('hla_b__isnull', False), ('hla_dqb1__isnull', True), ('hla_drb1__isnull', True), ('hla_drb__isnull', True)), models.Q(('hla_a__isnull', True), ('hla_b__isnull', True), ('hla_dqb1__isnull', True), ('hla_drb1__isnull', False), ('hla_drb__isnull', True)), models.Q(('hla_a__isnull', True), ('hla_b__isnull', True), ('hla_dqb1__isnull', True), ('hla_drb1__isnull', True), ('hla_drb__isnull', False)), models.Q(('hla_a__isnull', True), ('hla_b__isnull', True), ('hla_dqb1__isnull', False), ('hla_drb1__isnull', True), ('hla_drb__isnull', True)), _connector='OR'), name='recipientuammfi_exactly_one_hla'), models.UniqueConstraint(condition=models.Q(('hla_a__isnull', False)), fields=('recipient', 'hla_a'), name='recipientuammfi_unique_hla_a'), models.UniqueConstraint(condition=models.Q(('hla_b__isnull', False)), fields=('recipient', 'hla_b'), name='recipientuammfi_unique_hla_b'), models.UniqueConstraint(condition=models.Q(('hla_drb1__isnull', False)), fields=('recipient', 'hla_drb1'), name='recipientuammfi_unique_hla_drb1'), models.UniqueConstraint(condition=models.Q(('hla_drb__isnull', False)), fields=('recipient', 'hla_drb'), name='recipientuammfi_unique_hla_drb'), models.UniqueConstraint(condition=models.Q(('hla_dqb1__isnull', False)), fields=('recipient', 'hla_dqb1'), name='recipientuammfi_unique_hla_dqb1')],
            },
        ),
    ]
