# Generated by Django 5.2.1 on 2025-07-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0011_donortest_first_name_donortest_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadaverdonor',
            name='status',
            field=models.CharField(choices=[('1', 'Cadaver Donor'), ('2', 'Living Donor')], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='donortest',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='donortest',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='livingdonor',
            name='status',
            field=models.CharField(choices=[('1', 'Cadaver Donor'), ('2', 'Living Donor')], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='recipienttest',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='recipienttest',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='نام خانوادگی'),
        ),
    ]
