# Generated by Django 5.2.1 on 2026-09-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0011_recipientuammfi'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientuammfi',
            name='participates_in_filter',
            field=models.BooleanField(default=True, verbose_name='شرکت در فیلترینگ'),
        ),
    ]
