# Generated by Django 5.2.1 on 2025-07-31 05:39

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0012_alter_cadaverdonor_status_alter_donortest_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='donor_blood_group',
            field=multiselectfield.db.fields.MultiSelectField(help_text='این مقدار توسط سیستیم تعین می گردد', max_length=200, verbose_name='گروه خونی مناسب برای دهنده'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='max_donor_age',
            field=models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداکثر سن مناسب برای دهنده'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='min_donor_age',
            field=models.IntegerField(help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداقل سن مناسب برای دهنده'),
        ),
    ]
