# Generated by Django 5.2.1 on 2025-07-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0013_alter_recipient_donor_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='min_donor_age',
            field=models.IntegerField(default=0, help_text='این مقدار توسط سیستیم تعین می گردد', verbose_name='حداقل سن مناسب برای دهنده'),
        ),
    ]
