# Generated by Django 5.2.1 on 2025-09-02 15:50

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0014_alter_recipient_min_donor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='hla_a_uam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_a_1_uam', to='referees.hlaa', verbose_name='HLA A (UAM)'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hla_b_uam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_b_1_uam', to='referees.hlab', verbose_name='HLA B (UAM)'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hla_dqb1_uam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_dqb1_1_uam', to='referees.hladqb1', verbose_name='HLA DQB1 (UAM)'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hla_drb1_uam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb1_1_uam', to='referees.hladrb1', verbose_name='HLA DRB1 (UAM)'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hla_drb_uam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hla_drb_1_uam', to='referees.hladrb', verbose_name='HLA DRB (UAM)'),
        ),
        migrations.AlterField(
            model_name='cadaverdonor',
            name='recipient_blood_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=2, verbose_name='گروه خونی مناسب برای گیرنده'),
        ),
        migrations.AlterField(
            model_name='livingdonor',
            name='recipient_blood_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=2, verbose_name='گروه خونی مناسب برای گیرنده'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='donor_blood_group',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], help_text='این مقدار توسط سیستیم تعین می گردد', max_length=2, verbose_name='گروه خونی مناسب برای دهنده'),
        ),
    ]
