# Generated by Django 5.2.1 on 2025-09-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0015_recipient_hla_a_uam_recipient_hla_b_uam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='hla_a_uam',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='hla_b_uam',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='hla_dqb1_uam',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='hla_drb1_uam',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='hla_drb_uam',
        ),
        migrations.AddField(
            model_name='recipient',
            name='hla_a_uam',
            field=models.ManyToManyField(blank=True, null=True, related_name='hla_a_1_uam', to='referees.hlaa', verbose_name='HLA A (UAM)'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hla_b_uam',
            field=models.ManyToManyField(blank=True, null=True, related_name='hla_b_1_uam', to='referees.hlab', verbose_name='HLA B (UAM)'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hla_dqb1_uam',
            field=models.ManyToManyField(blank=True, null=True, related_name='hla_dqb1_1_uam', to='referees.hladqb1', verbose_name='HLA DQB1 (UAM)'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hla_drb1_uam',
            field=models.ManyToManyField(blank=True, null=True, related_name='hla_drb1_1_uam', to='referees.hladrb1', verbose_name='HLA DRB1 (UAM)'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='hla_drb_uam',
            field=models.ManyToManyField(blank=True, null=True, related_name='hla_drb_1_uam', to='referees.hladrb', verbose_name='HLA DRB (UAM)'),
        ),
    ]
