# Generated by Django 5.2.1 on 2025-09-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0017_alter_recipient_hla_a_uam_alter_recipient_hla_b_uam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='class_i_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recipient_pdf/', verbose_name='Class I PDF'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='class_ii_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recipient_pdf/', verbose_name='Class II PDF'),
        ),
    ]
