# Generated by Django 5.2.1 on 2025-09-10 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0018_recipient_class_i_pdf_recipient_class_ii_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='UAMWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hla_base', models.CharField(max_length=30, verbose_name='HLA')),
                ('message', models.TextField(verbose_name='پیغام')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uam_warnings', to='referees.recipient', verbose_name='گیرنده')),
            ],
        ),
    ]
