# Generated by Django 5.2.1 on 2025-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0019_uamwarning'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='read_uam_from',
            field=models.CharField(choices=[('1', 'از لیست های ارسالی'), ('2', 'از فایل های ارسالی')], default='1', verbose_name='تحلیل UAM از؟'),
        ),
    ]
