# Generated by Django 5.2.1 on 2025-09-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0020_recipient_read_uam_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='gender',
            field=models.CharField(choices=[('1', 'مرد'), ('2', 'زن')], default='1', verbose_name='جنسیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='pregnancies_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد بارداری'),
        ),
    ]
