# Generated by Django 5.2.1 on 2025-09-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0021_recipient_gender_recipient_pregnancies_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='pregnancies_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد بارداری (اختیاری)'),
        ),
    ]
