# Generated by Django 5.2.1 on 2025-09-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0022_alter_recipient_pregnancies_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadaverdonor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cadaverdonor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='livingdonor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='livingdonor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='cadaverdonor',
            name='full_name',
            field=models.CharField(default='لیلا', max_length=200, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadaverdonor',
            name='pcr_based_pdf',
            field=models.FileField(blank=True, null=True, upload_to='donor_pdf/', verbose_name='PCR Based PDF'),
        ),
        migrations.AddField(
            model_name='livingdonor',
            name='full_name',
            field=models.CharField(default='علی', max_length=200, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livingdonor',
            name='pcr_based_pdf',
            field=models.FileField(blank=True, null=True, upload_to='donor_pdf/', verbose_name='PCR Based PDF'),
        ),
        migrations.AlterField(
            model_name='cadaverdonor',
            name='national_code',
            field=models.CharField(max_length=15, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='livingdonor',
            name='national_code',
            field=models.CharField(max_length=15, verbose_name='کد ملی'),
        ),
    ]
