# Generated by Django 5.2.1 on 2025-09-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0023_remove_cadaverdonor_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadaverdonor',
            name='gender',
            field=models.CharField(choices=[('1', 'مرد'), ('2', 'زن')], default='1', verbose_name='جنسیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadaverdonor',
            name='pregnancies_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد بارداری (اختیاری)'),
        ),
        migrations.AddField(
            model_name='livingdonor',
            name='gender',
            field=models.CharField(choices=[('1', 'مرد'), ('2', 'زن')], default='1', verbose_name='جنسیت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livingdonor',
            name='pregnancies_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='تعداد بارداری (اختیاری)'),
        ),
    ]
