# Generated by Django 5.2.1 on 2025-09-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0024_cadaverdonor_gender_cadaverdonor_pregnancies_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='pcr_based_pdf',
            field=models.FileField(blank=True, null=True, upload_to='recipient_pdf/', verbose_name='PCR Based PDF'),
        ),
    ]
