# Generated by Django 5.2.1 on 2025-09-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0025_recipient_pcr_based_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='recipient',
            name='full_name',
            field=models.CharField(default='وو', max_length=200, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='national_code',
            field=models.CharField(max_length=15, verbose_name='کد ملی'),
        ),
    ]
