# Generated by Django 5.2.1 on 2025-10-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referees', '0026_remove_recipient_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='candidate_for_2_kidney_TX',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='candidate_for_kidney_after_other_organ_TX',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='cpra',
            field=models.CharField(blank=True, choices=[('1', '≥ 98%'), ('2', '95-97%'), ('3', 'none')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='desensitized',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='dialysis_duration',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='medical_urgency',
            field=models.CharField(blank=True, choices=[('1', 'no access'), ('2', 'cardiomyopathy'), ('3', 'none')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='previous_donation',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='waiting_list',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
